name: Build and test

on:
  push:
    branches: [ master, main ]
    tags: ["*"]
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'src/docs/**'

  pull_request:
    branches: [ master, main ]

jobs:
  build:
    uses: arturopala/workflows/.github/workflows/build.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}
      